In [1]:
ONEDIR = '/home/r/Downloads/Java/src/testcases/CWE760_Predictable_Salt_One_Way_Hash/'

In [2]:
import os

def read_testcases_from_dir(directory):
    testcases = []
    for name in os.listdir(directory):
        if name.startswith('CWE'):
            full = os.path.join(directory, name)
            with open(full, 'r') as testcase:
                testcases.append(testcase.read())
    return testcases

In [3]:
testcases = read_testcases_from_dir(ONEDIR)

In [4]:
print(testcases[0])

/* TEMPLATE GENERATED TESTCASE FILE
Filename: CWE760_Predictable_Salt_One_Way_Hash__basic_06.java
Label Definition File: CWE760_Predictable_Salt_One_Way_Hash__basic.label.xml
Template File: point-flaw-06.tmpl.java
*/
/*
* @description
* CWE: 760 Use of one-way hash with a predictable salt
* Sinks:
*    GoodSink: SHA512 with a sufficiently random salt
*    BadSink : SHA512 with a predictable salt
* Flow Variant: 06 Control flow: if(PRIVATE_STATIC_FINAL_FIVE==5) and if(PRIVATE_STATIC_FINAL_FIVE!=5)
*
* */

package testcases.CWE760_Predictable_Salt_One_Way_Hash;

import testcasesupport.*;

import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Random;

public class CWE760_Predictable_Salt_One_Way_Hash__basic_06 extends AbstractTestCase
{
    /* The variable below is declared "final", so a tool should be able
     * to identify that reads of this will always give its initialized
     * value.
     */
    private static final int PRIVATE_STATIC_FINAL_FIVE = 

In [5]:
part = '''public class CWE760_Predictable_Salt_One_Way_Hash__basic_16 extends AbstractTestCase
{
    public void bad() throws Throwable
    {
        while(true)
        {
            Random random = new Random();
            MessageDigest hash = MessageDigest.getInstance("SHA-512");
            /* FLAW: SHA512 with a predictable salt */
            hash.update((Integer.toString(random.nextInt())).getBytes("UTF-8"));
            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));
            IO.writeLine(IO.toHex(hashValue));
            break;
        }
    }

    /* good1() change the conditions on the while statements */
    private void good1() throws Throwable'''

In [6]:
part

'public class CWE760_Predictable_Salt_One_Way_Hash__basic_16 extends AbstractTestCase\n{\n    public void bad() throws Throwable\n    {\n        while(true)\n        {\n            Random random = new Random();\n            MessageDigest hash = MessageDigest.getInstance("SHA-512");\n            /* FLAW: SHA512 with a predictable salt */\n            hash.update((Integer.toString(random.nextInt())).getBytes("UTF-8"));\n            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));\n            IO.writeLine(IO.toHex(hashValue));\n            break;\n        }\n    }\n\n    /* good1() change the conditions on the while statements */\n    private void good1() throws Throwable'

In [7]:
import re
# re not enough
print(re.findall('([private|public]\ [^class].*?\{.*?\})', testcases[0], re.MULTILINE | re.DOTALL)[1])

e void good1() throws Throwable
    {
        if (PRIVATE_STATIC_FINAL_FIVE != 5)
        {
            /* INCIDENTAL: CWE 561 Dead Code, the code below will never run */
            IO.writeLine("Benign, fixed string");
        }


In [8]:
import javalang

tree = javalang.parse.parse("package javalang.brewtab.com; class Test {}")

In [9]:
tree = javalang.parse.parse(testcases[0])

In [ ]:
#overkill and language-specific
#for path, node in tree:
#    print(path, node)

In [10]:
one = testcases[0]

In [11]:
print(one)

/* TEMPLATE GENERATED TESTCASE FILE
Filename: CWE760_Predictable_Salt_One_Way_Hash__basic_06.java
Label Definition File: CWE760_Predictable_Salt_One_Way_Hash__basic.label.xml
Template File: point-flaw-06.tmpl.java
*/
/*
* @description
* CWE: 760 Use of one-way hash with a predictable salt
* Sinks:
*    GoodSink: SHA512 with a sufficiently random salt
*    BadSink : SHA512 with a predictable salt
* Flow Variant: 06 Control flow: if(PRIVATE_STATIC_FINAL_FIVE==5) and if(PRIVATE_STATIC_FINAL_FIVE!=5)
*
* */

package testcases.CWE760_Predictable_Salt_One_Way_Hash;

import testcasesupport.*;

import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Random;

public class CWE760_Predictable_Salt_One_Way_Hash__basic_06 extends AbstractTestCase
{
    /* The variable below is declared "final", so a tool should be able
     * to identify that reads of this will always give its initialized
     * value.
     */
    private static final int PRIVATE_STATIC_FINAL_FIVE = 

In [12]:
from pyparsing import *

In [13]:
SIGNATURE = (oneOf('private public')
             + NotAny('class') 
             + Regex('.*').setResultsName('actual_signature')
             + '{'# + Regex(r'.*', flags=re.M|re.DOTALL) + '}' + LineEnd()
            )  

In [14]:
def rem_comm(code):
    return re.sub('\/\*.*\*\/', '', code)

In [15]:
def get_methods(source_text):
    results = list(SIGNATURE.scanString(source_text))
    methods = []
    labels = []
    for i in range(len(results) - 1):
        signature = results[i][0][1]
        vulnerable = 'bad' in signature
        method = rem_comm(source_text[results[i][1] : results[i+1][1]])
        methods.append(method)
        labels.append(vulnerable)
    return methods, labels

In [16]:
methods, labels = get_methods(one)
print(methods[0])
print(labels[0])

public void bad() throws Throwable
    {
        if (PRIVATE_STATIC_FINAL_FIVE == 5)
        {
            Random random = new Random();
            MessageDigest hash = MessageDigest.getInstance("SHA-512");
            
            hash.update((Integer.toString(random.nextInt())).getBytes("UTF-8"));
            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));
            IO.writeLine(IO.toHex(hashValue));
        }
    }

    
    
True


In [17]:
upto = one[1580: 2346]
print(rem_comm(upto))

private void good1() throws Throwable
    {
        if (PRIVATE_STATIC_FINAL_FIVE != 5)
        {
            
            IO.writeLine("Benign, fixed string");
        }
        else
        {

            SecureRandom secureRandom = new SecureRandom();

            MessageDigest hash = MessageDigest.getInstance("SHA-512");
            
            SecureRandom prng = SecureRandom.getInstance("SHA1PRNG");
            hash.update(prng.generateSeed(32));
            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));

            IO.writeLine(IO.toHex(hashValue));

        }
    }

    
    


In [18]:
JULIET = '/home/r/Downloads/Java/src/testcases/'

In [19]:
from glob import glob

In [20]:
JGLOB = JULIET + '/*/CWE*.java'

In [21]:
def read_all_from_glob(expression):
    testcases = []
    for name in glob(expression):
        with open(name, 'r') as testcase:
            testcases.append(testcase.read())
    return testcases

In [23]:
%%time
all_files = read_all_from_glob(JGLOB)

CPU times: user 312 ms, sys: 95.3 ms, total: 407 ms
Wall time: 408 ms


In [24]:
len(all_files)

11164

In [27]:
all_files[:3]

['/* TEMPLATE GENERATED TESTCASE FILE\nFilename: CWE759_Unsalted_One_Way_Hash__basic_15.java\nLabel Definition File: CWE759_Unsalted_One_Way_Hash__basic.label.xml\nTemplate File: point-flaw-15.tmpl.java\n*/\n/*\n* @description\n* CWE: 759 Use of one-way hash with no salt\n* Sinks:\n*    GoodSink: use a sufficiently random salt\n*    BadSink : SHA512 with no salt\n* Flow Variant: 15 Control flow: switch(7)\n*\n* */\n\npackage testcases.CWE759_Unsalted_One_Way_Hash;\n\nimport testcasesupport.*;\n\nimport java.security.MessageDigest;\nimport java.security.SecureRandom;\n\npublic class CWE759_Unsalted_One_Way_Hash__basic_15 extends AbstractTestCase\n{\n    public void bad() throws Throwable\n    {\n        switch (7)\n        {\n        case 7:\n            MessageDigest hash = MessageDigest.getInstance("SHA-512");\n            /* FLAW: SHA512 with no salt */\n            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));\n            IO.writeLine(IO.toHex(hashValue));\n         

In [28]:
def get_all_methods(all_files):
    all_methods = []
    all_labels  = []
    for testcase in all_files:
        methods, labels = get_methods(testcase)
        all_methods += methods
        all_labels  += labels
    return all_methods, all_labels

In [29]:
%%time

all_methods, all_labels = get_all_methods(all_files)

CPU times: user 1min 38s, sys: 51.8 ms, total: 1min 38s
Wall time: 1min 38s


In [30]:
for meth in all_methods[:3]:
    print('------')
    print(meth)
    print('------')

------
public void bad() throws Throwable
    {
        switch (7)
        {
        case 7:
            MessageDigest hash = MessageDigest.getInstance("SHA-512");
            
            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));
            IO.writeLine(IO.toHex(hashValue));
            break;
        default:
            
            IO.writeLine("Benign, fixed string");
            break;
        }
    }

    
    
------
------
private void good1() throws Throwable
    {
        switch (8)
        {
        case 7:
            
            IO.writeLine("Benign, fixed string");
            break;
        default:
            MessageDigest hash = MessageDigest.getInstance("SHA-512");
            
            SecureRandom prng = SecureRandom.getInstance("SHA1PRNG");
            hash.update(prng.generateSeed(32));
            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));
            IO.writeLine(IO.toHex(hashValue));
            break;
        }
    }

In [31]:
print(all_methods[0])
print(all_labels[0])
first100methods = all_methods[:100]

public void bad() throws Throwable
    {
        switch (7)
        {
        case 7:
            MessageDigest hash = MessageDigest.getInstance("SHA-512");
            
            byte[] hashValue = hash.digest("hash me".getBytes("UTF-8"));
            IO.writeLine(IO.toHex(hashValue));
            break;
        default:
            
            IO.writeLine("Benign, fixed string");
            break;
        }
    }

    
    
True


In [32]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [33]:
NUM_WORDS = 1000
keras_tokenizer = Tokenizer(NUM_WORDS,
                            filters='\t\n',
                            lower=True,
                            split=' ',
                            char_level=False)

In [ ]:
?Tokenizer

In [34]:
%%time
keras_tokenizer.fit_on_texts(all_methods)

CPU times: user 1.65 s, sys: 24 ms, total: 1.68 s
Wall time: 1.68 s


In [61]:
print(str(keras_tokenizer.word_counts)[:1000])

OrderedDict([('public', 15676), ('void', 25995), ('bad()', 5125), ('throws', 26778), ('throwable', 26746), ('{', 186876), ('switch', 1279), ('(7)', 405), ('case', 1415), ('7:', 555), ('messagedigest', 658), ('hash', 96), ('=', 127781), ('messagedigest.getinstance("sha-512");', 326), ('byte[]', 1250), ('hashvalue', 240), ('hash.digest("hash', 96), ('me".getbytes("utf-8"));', 96), ('io.writeline(io.tohex(hashvalue));', 240), ('break;', 3770), ('default:', 1253), ('io.writeline("benign,', 2402), ('fixed', 2402), ('string");', 2402), ('}', 186580), ('private', 13009), ('good1()', 1222), ('(8)', 150), ('securerandom', 410), ('prng', 62), ('securerandom.getinstance("sha1prng");', 62), ('hash.update(prng.generateseed(32));', 62), ('good2()', 951), ('if', 50029), ('(5', 607), ('==', 2844), ('5)', 3499), ('!=', 29933), ('else', 14227), ('good()', 2074), ('good1();', 111), ('(io.staticreturnstrueorfalse())', 404), ('(', 3476), ('privatetrue)', 822), ('privatefalse)', 307), ('(private_static_fina

In [36]:
keras_tokenizer.document_count

31105

In [65]:
print(str(keras_tokenizer.word_index)[:200])#['{' : 'string']

{'{': 1, '}': 2, '=': 3, 'if': 4, 'data': 5, 'catch': 6, 'try': 7, 'null;': 8, 'io.logger.log(level.warning,': 9, 'string': 10, '!=': 11, 'new': 12, '"error': 13, 'null)': 14, 'the': 15, 'throws': 16,


In [66]:
%%time
sequences = keras_tokenizer.texts_to_sequences(all_methods)

CPU times: user 1.34 s, sys: 8.02 ms, total: 1.35 s
Wall time: 1.35 s


In [69]:
print(sequences[0])

[24, 18, 69, 16, 17, 1, 230, 510, 1, 213, 446, 381, 845, 3, 534, 238, 567, 3, 846, 847, 568, 80, 237, 122, 123, 124, 80, 2, 2]


In [70]:
lengths = [len(s) for s in sequences]

In [71]:
import numpy as np
import pandas as pd

In [72]:
lenspd = pd.DataFrame(lengths)

In [73]:
lenspd[0].describe()

count    31105.000000
mean        68.165022
std         66.613902
min          1.000000
25%         13.000000
50%         40.000000
75%        112.000000
max        551.000000
Name: 0, dtype: float64

In [75]:
from keras.preprocessing.sequence import pad_sequences

In [76]:
PAD_SIZE = 40
padded_seqs = pad_sequences(sequences,
                            maxlen=PAD_SIZE,
                            padding='post')

In [77]:
len(sequences[0])

29

In [79]:
len(padded_seqs[0])

40

In [80]:
padded_seqs[0]

array([ 24,  18,  69,  16,  17,   1, 230, 510,   1, 213, 446, 381, 845,
         3, 534, 238, 567,   3, 846, 847, 568,  80, 237, 122, 123, 124,
        80,   2,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0], dtype=int32)

In [81]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [82]:
MODEL = Sequential()
MODEL.add(Embedding(NUM_WORDS,            #input dimension
                    100,                  #output dimension
                    input_length=PAD_SIZE #input length. != input_dim???
                   ))
MODEL.add(Flatten())
MODEL.add(Dense(1, activation='sigmoid'))
MODEL.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['acc'])
MODEL.summary()

W0930 14:20:51.878893 140692704020288 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0930 14:20:51.895741 140692704020288 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0930 14:20:51.899592 140692704020288 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0930 14:20:51.935948 140692704020288 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0930 14:20:51.959682 140692704020288 deprecation_wrappe

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 40, 100)           100000    
_________________________________________________________________
flatten_1 (Flatten)          (None, 4000)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 4001      
Total params: 104,001
Trainable params: 104,001
Non-trainable params: 0
_________________________________________________________________


In [ ]:
?Embedding

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
?train_test_split

In [85]:
X_train, X_test, y_train, y_test =\
train_test_split(padded_seqs, all_labels,
                 test_size = 0.2,
                 random_state=0)

In [86]:
%%time
MODEL.fit(X_train, y_train,
          epochs = 20,
          validation_split = 0.2)

W0930 14:21:05.011180 140692704020288 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 19907 samples, validate on 4977 samples
Epoch 1/20
19907/19907 [==============================] - 2s 82us/step - loss: 0.3124 - acc: 0.8351 - val_loss: 0.2460 - val_acc: 0.8640
Epoch 2/20
19907/19907 [==============================] - 1s 70us/step - loss: 0.2370 - acc: 0.8644 - val_loss: 0.2408 - val_acc: 0.8712
Epoch 3/20
19907/19907 [==============================] - 1s 69us/step - loss: 0.2273 - acc: 0.8665 - val_loss: 0.2315 - val_acc: 0.8656
Epoch 4/20
19907/19907 [==============================] - 1s 73us/step - loss: 0.2225 - acc: 0.8678 - val_loss: 0.2274 - val_acc: 0.8680
Epoch 5/20
19907/19907 [==============================] - 1s 75us/step - loss: 0.2205 - acc: 0.8668 - val_loss: 0.2337 - val_acc: 0.8714
Epoch 6/20
19907/19907 [==============================] - 1s 70us/step - loss: 0.2190 - acc: 0.8669 - val_loss: 0.2279 - val_acc: 0.8714
Epoch 7/20
19907/19907 [==============================] - 1s 73us/step - loss: 0.2166 - acc: 0.8693 - val_loss: 0.2245 - val_acc:

In [87]:
loss, acc = MODEL.evaluate(X_test, y_test, verbose=1)

6221/6221 [==============================] - 0s 20us/step


In [90]:
acc

0.8624015431794261

In [91]:
X_test[0]

array([179,   2,   6, 169, 182,   1, 185, 186, 187, 118, 188, 189, 190,
        92,   3, 132,   2,   4, 479,  79, 477, 128,  92, 451,  85,   1,
       126, 135, 191, 121,  77, 108, 141,   1, 139, 184,   2,   2,   2,
         2], dtype=int32)

In [92]:
sec_rand = 'good good SecureRandom secureRandom = new SecureRandom();\nIO.writeLine("" + secureRandom.nextDouble());'
bad_rand = 'IO.writeLine("" + Math.random());'
naive_tests = [sec_rand, bad_rand]

In [93]:
#keras_tokenizer.fit_on_texts(naive_tests)
naive_seqs = keras_tokenizer.texts_to_sequences(naive_tests)

In [94]:
naive_seqs

[[507, 507, 3, 12, 680, 242, 23], [242, 23]]

In [95]:
padded_naive = pad_sequences(naive_seqs,
                             maxlen=PAD_SIZE,
                             padding='post')

In [96]:
padded_naive

array([[507, 507,   3,  12, 680, 242,  23,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [242,  23,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0]], dtype=int32)

In [97]:
MODEL.predict(padded_naive)

array([[0.00837098],
       [0.02838966]], dtype=float32)

In [98]:
predicts = MODEL.predict(X_test)
predicts.flatten()

array([2.6106834e-05, 3.9422607e-01, 2.4902821e-04, ..., 3.9422607e-01,
       9.9996674e-01, 2.8568105e-04], dtype=float32)

In [101]:
print(str(y_test)[:100])

[False, True, False, False, False, True, False, False, False, True, False, True, False, False, False


In [102]:
pd.DataFrame([predicts.flatten(), y_test])

0         1            2            3            4         5     \
0  2.61068e-05  0.394226  0.000249028  2.46763e-05  4.58956e-06  0.394226   
1        False      True        False        False        False      True   

        6            7            8         9        ...           6211  \
0  0.0520131  0.000917643  8.51452e-05  0.999983     ...       0.300954   
1      False        False        False      True     ...          False   

          6212        6213     6214      6215     6216      6217      6218  \
0  0.000123084  0.00105029  0.99987  0.430299  0.33364  0.466879  0.394226   
1        False       False     True     False    False      True      True   

       6219         6220  
0  0.999967  0.000285681  
1      True        False  

[2 rows x 6221 columns]